---
resources:
- name: build-code
  type: git
  source:
    uri: https://github.com/ianmiell/alert-on-change
    branch: master

jobs:
- name: Builder
  plan:
  - get: build-code
    trigger: true
  - task: build-thing
    config:
      platform: linux
      inputs:
        - name: build-code
      outputs:
        - name: export-directory
      image_resource:
        type: docker-image
        source:
          repository: debian
      run:
        path: sh
        args:
        - -exc
        - |
          touch export-directory/mything
          ls -lRt
  - task: push-thing
    config:
      platform: linux
      inputs:
        - name: export-directory
      image_resource:
        type: docker-image
        source:
          repository: debian
      run:
        path: sh
        args:
        - -exc
        - |
          ls export-directory
