---
jobs:
- name: Builder
  plan:
  - task: build-thing
    params:
      FIRSTSECRET: ((firstsecret.asecret))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: debian
      run:
        path: sh
        args:
        - -exc
        - |
          echo here
          echo $FIRSTSECRET
